name: solver_CPack_0

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build
        run: |
          mkdir _build && cd _build
          cmake .. -DCPACK_GENERATOR="TGZ"
          cmake --build . --target package
          
          cpack -G "DEB"
          cpack -G "RPM"
          
          mkdir ../artifacts
          mv *.tar.gz ../artifacts/
          mv *.deb ../artifacts/
          mv *.rpm ../artifacts
          
      - name: Public
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts
